// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422024312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Thời trang Nam",
                            Description = "Áo thun nam cổ tròn nam tính, chất liệu 100% cotton thoáng mát, thấm hút mồ hôi cực tốt. Thiết kế basic dễ dàng phối cùng nhiều loại trang phục đi chơi, dạo phố.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Thun Cổ Tròn Xanh",
                            Price = 250000m,
                            SalePrice = 199000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Thời trang Nam",
                            Description = "Quần Jean phom Slimfit tôn dáng, chất denim co giãn 4 chiều mang lại sự thoải mái tối đa kể cả khi vận động. Phù hợp mặc đi làm hoặc đi tiệc.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=500&q=80",
                            Name = "Quần Jean Nam Slimfit",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Thời trang Nam",
                            Description = "Áo sơ mi vải Oxford dày dặn, đứng form chuẩn công sở. Bề mặt vải chống nhắn tối ưu giúp người mặc luôn tươm tất suốt cả ngày.",
                            ImageUrl = "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Sơ Mi Trắng Oxford",
                            Price = 350000m,
                            SalePrice = 290000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Thời trang Nam",
                            Description = "Quần short kaki trẻ trung và năng động với túi 2 bên hông sâu tiện lợi. Chất vải mịn, bền màu sau nhiều lần giặt.",
                            ImageUrl = "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=500&q=80",
                            Name = "Quần Shorts Kaki Nam",
                            Price = 220000m,
                            SalePrice = 150000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Thời trang Nam",
                            Description = "Áo thun có cổ phong cách lịch thiệp, dễ mặc và tôn vai. Chất vải cá sấu (Lacoste) thông thoáng, thân thiện với làn da.",
                            ImageUrl = "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Polo Nam Form Regular",
                            Price = 320000m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Thời trang Nam",
                            Description = "Áo khoác đi gió phong cách quân đội cá tính, form ôm vừa vặn, giữ ấm và che mưa lất phất cực tốt.",
                            ImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Khoác Bomber Nam",
                            Price = 550000m,
                            SalePrice = 450000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Thời trang Nữ",
                            Description = "Váy voan nhẹ nhàng, bay bổng, hoạ tiết hoa mùa hè nữ tính. Rất thích hợp cho những chuyến dã ngoại, dạo biển và chụp hình sống ảo.",
                            ImageUrl = "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=500&q=80",
                            Name = "Váy Nữ Mùa Hè",
                            Price = 550000m,
                            SalePrice = 420000m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Thời trang Nữ",
                            Description = "Thiết kế cổ vuông tôn xương quai xanh quyến rũ. Áo có chi tiết bo thun tay tạo nét tiểu thư thanh lịch.",
                            ImageUrl = "https://images.unsplash.com/photo-1550614000-4b95d415f3f0?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Dài Tay Cổ Vuông",
                            Price = 280000m,
                            SalePrice = 199000m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Thời trang Nữ",
                            Description = "Chân váy đen phối khoá lưng đơn giản, che khuyết điểm đùi tốt, luôn là item must-have trong tủ đồ phái đẹp.",
                            ImageUrl = "https://images.unsplash.com/photo-1583496661160-c5dcb4c6f1bc?auto=format&fit=crop&w=500&q=80",
                            Name = "Chân Váy Chữ A Công Sở",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Thời trang Nữ",
                            Description = "Set bộ ngủ vải đũi cao cấp, cực mát mẻ cho những ngày oi bức. An toàn và nịnh da nhạy cảm.",
                            ImageUrl = "https://images.unsplash.com/photo-1601056588266-96a8eff52f4c?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồ Bộ Đũi Mặc Nhà",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Thời trang Nữ",
                            Description = "Blazer dáng rộng Hàn Quốc siêu hack dáng. Vải tuýt xi đứng form, không sợ xù lông, mặc được đa mùa.",
                            ImageUrl = "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=500&q=80",
                            Name = "Áo Blazer Hàn Quốc",
                            Price = 650000m,
                            SalePrice = 590000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Giày dép",
                            Description = "Giày thể thao êm ái, bám đường, công nghệ đệm khí đàn hồi siêu nhẹ, hỗ trợ tối đa việc chạy bộ hoặc mang thời trang đường phố.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80",
                            Name = "Giày Sneaker Thể Thao",
                            Price = 850000m,
                            SalePrice = 750000m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Giày dép",
                            Description = "Thiết kế giày cao gót 7 phân, lót nhung êm ái, phù hợp mang công sở nguyên ngày dài mà không đau chân.",
                            ImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=500&q=80",
                            Name = "Giày Cao Gót Mũi Nhọn",
                            Price = 450000m,
                            SalePrice = 350000m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Giày dép",
                            Description = "Dép đúc nguyên khối Eva dẻo, đi nước thoải mái không lo trơn trượt. Hot trend của mùa hè năm nay.",
                            ImageUrl = "https://images.unsplash.com/photo-1562183241-b937e95585b6?auto=format&fit=crop&w=500&q=80",
                            Name = "Dép Bánh Mì Cao Su",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Giày dép",
                            Description = "Giày da bò nguyên tấm sang trọng, đường may nổi tỉ mỉ. Thích hợp tham dự sự kiện cao cấp.",
                            ImageUrl = "https://images.unsplash.com/photo-1614252232525-a111a47321ac?auto=format&fit=crop&w=500&q=80",
                            Name = "Giày Lười Loafer Da",
                            Price = 890000m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Giày dép",
                            Description = "Phiên bản giày chạy chuyên dụng có đế vát chéo, bám dính tốt với mọi bề mặt từ đường nhựa đến đồi núi.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=500&q=80",
                            Name = "Giày Chạy Bộ Nam",
                            Price = 1350000m,
                            SalePrice = 990000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Phụ kiện",
                            Description = "Balo đa năng có không gian rộng đủ để vừa laptop 15.6 inch. Chất liệu dù polyeste kháng nước 100% trong mọi cơn mưa rào.",
                            ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=500&q=80",
                            Name = "Balo Chống Nước Tiện Lợi",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Phụ kiện",
                            Description = "Kính mát Unisex gọng mảnh, tròng kính phân cực có tính năng cản 100% tia UV chói lóa.",
                            ImageUrl = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80",
                            Name = "Mắt Kính Thời Trang",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Phụ kiện",
                            Description = "Túi vải bố thân thiện môi trường, in hình đồ họa dễ thương. Vật bất ly thân của sinh viên.",
                            ImageUrl = "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=500&q=80",
                            Name = "Túi Tote Canvas",
                            Price = 90000m,
                            SalePrice = 55000m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Phụ kiện",
                            Description = "Thắt lưng da đan tinh tế, đầu khóa tự động đúc nguyên khối chống xước. Quà tặng ý nghĩa cho cánh mày râu.",
                            ImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=500&q=80",
                            Name = "Thắt Lưng Da Đan",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Phụ kiện",
                            Description = "Mũ baseball form mềm cất vừa cốp xe. Phía sau có khoá kim loại chỉnh size tuỳ ý chuẩn đầu Châu Á.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=500&q=80",
                            Name = "Mũ Lưỡi Trai Logo",
                            Price = 120000m,
                            SalePrice = 99000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Đồng hồ",
                            Description = "Mang âm hưởng hoàng gia, mặt kính Sapphire chống trầy xước kết hợp dây da cao cấp, tôn lên đẳng cấp cho người sở hữu.",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Đeo Tay Cổ Điển",
                            Price = 1200000m,
                            SalePrice = 990000m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Đồng hồ",
                            Description = "Kết nối smartphone bằng Bluetooth. Khả năng đo nhịp tim liên tục, cảnh báo sức khỏe và thời lượng pin dùng suốt 15 ngày.",
                            ImageUrl = "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Thông Minh X",
                            Price = 1800000m,
                            SalePrice = 1550000m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Đồng hồ",
                            Description = "Thiết kế mặt mảnh ôm sát thanh lịch, dây lưới linh hoạt thoáng khí có thể tự thay đổi không cần công cụ tháo nối.",
                            ImageUrl = "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Nữ Dây Lưới",
                            Price = 600000m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Đồng hồ",
                            Description = "Sinh ra cho dân phượt. Kháng nước ở độ sâu 100m, chống va đập siêu hạng bằng bộ ốc vít bằng thép titanium.",
                            ImageUrl = "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Thể Thao G",
                            Price = 2500000m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Đồng hồ",
                            Description = "Bộ máy Automatic phô diễn chân kính phức tạp. Tự lên cót dự trữ cót tối đa 72 giờ không cần đeo liên tục.",
                            ImageUrl = "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Cơ Lộ Mặt",
                            Price = 3500000m,
                            SalePrice = 2800000m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Đồng hồ",
                            Description = "Thiết kế tối giản hiển thị rõ giờ phút. Sử dụng mạch Pin Quartz chuẩn Nhật cho độ chính xác cực cao và bền bỉ theo vài năm.",
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=500&q=80",
                            Name = "Đồng Hồ Sinh Viên",
                            Price = 250000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
